[package]
name = "bgpd"
version = "0.1.0"
edition = "2021"
description = "BGP server implementation"
license = "GPL-3"

[dependencies]
tokio =  { version = "1.40.0", features = ["full"] }
anyhow = "1.0.89"
bgp-shared = { path = "../bgp-shared"}